#!/bin/sh
MYBUCKET=trendingtopics
DATEHOUR=`date --date "now +4 hours" +"%Y%m%d-%H"`

# fetch the latest wikistats files every hour
sleep 5m
cd tmp
wget -r --quiet --no-directories --no-parent -L -A "pagecounts-$DATEHOUR*" http://dammit.lt/wikistats/ 
# upload to s3 bucket
FILENAME=`ls pagecounts-$DATEHOUR*`
s3cmd --config=/root/.s3cfg put --force $FILENAME s3://$MYBUCKET/wikistats/$FILENAME 1> /dev/null
# in the daily job, periodically wipe local copies of the pagecounts files
cd ../
